from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import scripts.evaluate_short_iv_gt_long_conditional_management_3weeks as _base

LOGS = ROOT / "logs"
_base.DEFAULT_SELECTED_TRADES_CSV = LOGS / "short_iv_gt_long_best_delta_monday_close_selected_trades.csv"
_base.DEFAULT_OUTPUT_TRADES_CSV = (
    LOGS
    / "short_iv_gt_long_conditional_management_monday_close_3weeks_tp0sl35_up50sl35_basket36_novix_ivpremium20_selected_trades.csv"
)
_base.DEFAULT_OUTPUT_SUMMARY_CSV = (
    LOGS
    / "short_iv_gt_long_conditional_management_monday_close_3weeks_tp0sl35_up50sl35_basket36_novix_ivpremium20_summary.csv"
)
_base.DEFAULT_BASKET_CLOSE_THRESHOLD_PCT = 36.0
_base.DEFAULT_VIX_MAX_WEEKLY_CHANGE_UP_PCT = None
_base.DEFAULT_MIN_SHORT_OVER_LONG_IV_PREMIUM_PCT = 20.0
_base.DEFAULT_ABSTAIN_TAKE_PROFIT_PCT = 0.0
_base.DEFAULT_ABSTAIN_STOP_LOSS_PCT = 35.0
_base.DEFAULT_UP_TAKE_PROFIT_PCT = 50.0
_base.DEFAULT_UP_STOP_LOSS_PCT = 35.0
_base.ABSTAIN_METHOD_SIDE_TP_STOP_OVERRIDES = {}

_MONDAY_METHOD_SOURCE_POLICY_LABEL = (
    "best_combined_abstain_tp0_stop35_high_iv_or_piecewise_moderate_iv"
    "__up_tp50_stop35_debit_gt_5_5_short_iv_lt_40"
)
_MONDAY_METHOD_TARGETED_UP_SKIP_POLICY_LABEL = (
    f"{_MONDAY_METHOD_SOURCE_POLICY_LABEL}__up_70_75_negative_method_skip"
)
_MONDAY_METHOD_TARGETED_UP_SKIP_ABSTAIN_HALF_SIZE_POLICY_LABEL = (
    f"{_MONDAY_METHOD_TARGETED_UP_SKIP_POLICY_LABEL}__abstain_debit_gt_4_half_size"
)
_MONDAY_METHOD_MEDIAN25TREND_MLLOGREG56_FILTER_POLICY_LABEL = (
    f"{_MONDAY_METHOD_TARGETED_UP_SKIP_ABSTAIN_HALF_SIZE_POLICY_LABEL}"
    "__skip_abstain_median25trend__skip_up_mllogreg56_conf_90_100"
)
_MONDAY_METHOD_DEBIT_SENSITIVE_UP_FILTER_POLICY_LABEL = (
    f"{_MONDAY_METHOD_MEDIAN25TREND_MLLOGREG56_FILTER_POLICY_LABEL}__skip_up_debit_sensitive_methods"
)
_MONDAY_METHOD_FINAL_POLICY_LABEL = (
    f"{_MONDAY_METHOD_DEBIT_SENSITIVE_UP_FILTER_POLICY_LABEL}__skip_abstain_debit_sensitive_methods"
)
_MONDAY_BASE_POLICY_LABEL = f"{_MONDAY_METHOD_SOURCE_POLICY_LABEL}__base"
_base.BASE_BEST_COMBINED_POLICY_LABEL = _MONDAY_BASE_POLICY_LABEL
_base.BASE_BEST_COMBINED_METHOD_SIDE_EXIT_POLICY_LABEL = _MONDAY_METHOD_SOURCE_POLICY_LABEL
_base.BEST_COMBINED_METHOD_SIDE_EXIT_TARGETED_UP_SKIP_POLICY_LABEL = (
    _MONDAY_METHOD_TARGETED_UP_SKIP_POLICY_LABEL
)
_base.BEST_COMBINED_METHOD_SIDE_EXIT_TARGETED_UP_SKIP_ABSTAIN_HALF_SIZE_POLICY_LABEL = (
    _MONDAY_METHOD_TARGETED_UP_SKIP_ABSTAIN_HALF_SIZE_POLICY_LABEL
)
_base.BEST_COMBINED_METHOD_SIDE_EXIT_MEDIAN25TREND_MLLOGREG56_FILTER_POLICY_LABEL = (
    _MONDAY_METHOD_MEDIAN25TREND_MLLOGREG56_FILTER_POLICY_LABEL
)
_base.BEST_COMBINED_METHOD_SIDE_EXIT_DEBIT_SENSITIVE_UP_FILTER_POLICY_LABEL = (
    _MONDAY_METHOD_DEBIT_SENSITIVE_UP_FILTER_POLICY_LABEL
)
_base.BEST_COMBINED_METHOD_SIDE_EXIT_DEBIT_SENSITIVE_ABSTAIN_FILTER_POLICY_LABEL = (
    _MONDAY_METHOD_FINAL_POLICY_LABEL
)
_base.BEST_COMBINED_METHOD_SIDE_EXIT_POLICY_LABEL = _MONDAY_METHOD_FINAL_POLICY_LABEL
_base.BEST_COMBINED_POLICY_LABEL = _MONDAY_METHOD_FINAL_POLICY_LABEL
_base.BASE_BEST_COMBINED_SYMBOL_SIDE_LOOKBACK_FILTER_POLICY_LABEL = (
    f"{_MONDAY_BASE_POLICY_LABEL}__symbol_side_52w_lookback_pnl_nonnegative"
)
_base.BASE_BEST_COMBINED_METHOD_SIDE_EXIT_SYMBOL_SIDE_LOOKBACK_FILTER_POLICY_LABEL = (
    f"{_MONDAY_METHOD_SOURCE_POLICY_LABEL}__symbol_side_52w_lookback_pnl_nonnegative"
)
_base.BEST_COMBINED_SYMBOL_SIDE_LOOKBACK_FILTER_POLICY_LABEL = (
    f"{_MONDAY_METHOD_FINAL_POLICY_LABEL}__symbol_side_52w_lookback_pnl_nonnegative"
)
_base.BEST_COMBINED_METHOD_SIDE_EXIT_SYMBOL_SIDE_LOOKBACK_FILTER_POLICY_LABEL = (
    f"{_MONDAY_METHOD_FINAL_POLICY_LABEL}__symbol_side_52w_lookback_pnl_nonnegative"
)

_MONDAY_PORTFOLIO_POLICY_LABEL = f"{_MONDAY_METHOD_FINAL_POLICY_LABEL}__basket_close_36"
_base.BEST_COMBINED_SOURCE_BASKET_CLOSE_70_POLICY_LABEL = _MONDAY_PORTFOLIO_POLICY_LABEL
_base.BEST_COMBINED_PORTFOLIO_POLICY_LABEL = _MONDAY_PORTFOLIO_POLICY_LABEL
_base.BEST_COMBINED_PORTFOLIO_LIVE_POLICY_LABEL = f"{_MONDAY_PORTFOLIO_POLICY_LABEL}_live"
_base.BEST_COMBINED_PORTFOLIO_MLGBP72_ABSTAIN_FIRST_BREACH_POLICY_LABEL = (
    f"{_MONDAY_PORTFOLIO_POLICY_LABEL}__mlgbp72_abstain_first_breach"
)
_base.BEST_COMBINED_PORTFOLIO_MLGBP72_ABSTAIN_LAST_PRE_EXPIRATION_NEGATIVE_POLICY_LABEL = (
    f"{_MONDAY_PORTFOLIO_POLICY_LABEL}__mlgbp72_abstain_last_pre_expiration_negative"
)
_base.BEST_COMBINED_PORTFOLIO_MLGBP72_ABSTAIN_ROLL_FORWARD_ONE_WEEK_UP1_POLICY_LABEL = (
    f"{_MONDAY_PORTFOLIO_POLICY_LABEL}__mlgbp72_abstain_roll_forward_one_week_up1"
)
_base.BEST_COMBINED_PORTFOLIO_MLGBP72_ABSTAIN_ROLL_FORWARD_ONE_WEEK_UP2_POLICY_LABEL = (
    f"{_MONDAY_PORTFOLIO_POLICY_LABEL}__mlgbp72_abstain_roll_forward_one_week_up2"
)
_base.BEST_COMBINED_PORTFOLIO_MLGBP72_ABSTAIN_ROLL_SAME_WEEK_ATM_POLICY_LABEL = (
    f"{_MONDAY_PORTFOLIO_POLICY_LABEL}__mlgbp72_abstain_roll_same_week_atm"
)
_base.BEST_COMBINED_PORTFOLIO_MLGBP72_ABSTAIN_ROLL_BOTH_LEGS_SAME_WEEK_ATM_POLICY_LABEL = (
    f"{_MONDAY_PORTFOLIO_POLICY_LABEL}__mlgbp72_abstain_roll_both_legs_same_week_atm"
)
_base.BEST_COMBINED_PORTFOLIO_MLGBP72_ABSTAIN_TWO_SIDED_BUTTERFLY_POLICY_LABEL = (
    f"{_MONDAY_PORTFOLIO_POLICY_LABEL}__mlgbp72_abstain_two_sided_call_put_butterfly"
)
_base.BEST_COMBINED_PORTFOLIO_MLGBP72_ABSTAIN_TWO_SIDED_BUTTERFLY_W2_POLICY_LABEL = (
    f"{_MONDAY_PORTFOLIO_POLICY_LABEL}__mlgbp72_abstain_two_sided_call_put_butterfly_w2"
)
_base.BEST_COMBINED_PORTFOLIO_MLGBP72_ABSTAIN_TWO_SIDED_BUTTERFLY_W3_POLICY_LABEL = (
    f"{_MONDAY_PORTFOLIO_POLICY_LABEL}__mlgbp72_abstain_two_sided_call_put_butterfly_w3"
)

globals().update({name: getattr(_base, name) for name in dir(_base) if not name.startswith("__")})


def main() -> int:
    return _base.main()


if __name__ == "__main__":
    raise SystemExit(main())
