/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Analyses
         * @description List recent analyses for the current user.
         */
        get: operations["list_analyses_v1_analysis_get"];
        put?: never;
        /**
         * Create Analysis
         * @description Create and enqueue a single-symbol deep analysis (Pro+ gated).
         */
        post: operations["create_analysis_v1_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analysis/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis
         * @description Get full analysis results (for polling and display).
         */
        get: operations["get_analysis_v1_analysis__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analysis/{analysis_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis Status
         * @description Lightweight status endpoint for polling.
         */
        get: operations["get_analysis_status_v1_analysis__analysis_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtests */
        get: operations["list_backtests_v1_backtests_get"];
        put?: never;
        /** Create Backtest */
        post: operations["create_backtest_v1_backtests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/backtests/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare Backtests */
        post: operations["compare_backtests_v1_backtests_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/backtests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest */
        get: operations["get_backtest_v1_backtests__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/backtests/{run_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest Status */
        get: operations["get_backtest_status_v1_backtests__run_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/checkout-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Checkout Session */
        post: operations["create_checkout_session_v1_billing_checkout_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/portal-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Portal Session */
        post: operations["create_portal_session_v1_billing_portal_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe Webhook */
        post: operations["stripe_webhook_v1_billing_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daily-picks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest Daily Picks
         * @description Return the latest daily recommendations.
         *
         *     Pro+ feature gated via ensure_forecasting_access.
         */
        get: operations["get_latest_daily_picks_v1_daily_picks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daily-picks/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pipeline History
         * @description Return recent pipeline run history (Pro+ gated).
         */
        get: operations["get_pipeline_history_v1_daily_picks_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis Events */
        get: operations["analysis_events_v1_events_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/backtests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backtest Events */
        get: operations["backtest_events_v1_events_backtests__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/exports/{export_job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Events */
        get: operations["export_events_v1_events_exports__export_job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/scans/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan Events */
        get: operations["scan_events_v1_events_scans__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Export */
        post: operations["create_export_v1_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exports/{export_job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Export */
        get: operations["download_export_v1_exports__export_job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exports/{export_job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Export Status */
        get: operations["get_export_status_v1_exports__export_job_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forecasts/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Forecast */
        get: operations["get_forecast_v1_forecasts__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta */
        get: operations["get_meta_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scans */
        get: operations["list_scans_v1_scans_get"];
        put?: never;
        /** Create Scan */
        post: operations["create_scan_v1_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan */
        get: operations["get_scan_v1_scans__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{job_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan Recommendations */
        get: operations["get_scan_recommendations_v1_scans__job_id__recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/strategy-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Strategy Catalog */
        get: operations["get_strategy_catalog_v1_strategy_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_v1_templates_get"];
        put?: never;
        /** Create Template */
        post: operations["create_template_v1_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Template */
        get: operations["get_template_v1_templates__template_id__get"];
        put?: never;
        post?: never;
        /** Delete Template */
        delete: operations["delete_template_v1_templates__template_id__delete"];
        options?: never;
        head?: never;
        /** Update Template */
        patch: operations["update_template_v1_templates__template_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisDetailResponse */
        AnalysisDetailResponse: {
            /** Close Price */
            close_price?: number | null;
            /** Completed At */
            completed_at?: string | null;
            /** Configs Tested */
            configs_tested: number;
            /** Created At */
            created_at?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Error Message */
            error_message?: string | null;
            /** Forecast */
            forecast?: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: string;
            /** Landscape */
            landscape?: {
                [key: string]: unknown;
            }[] | null;
            /** Regime */
            regime?: {
                [key: string]: unknown;
            } | null;
            /** Stage */
            stage: string;
            /** Status */
            status: string;
            /** Strategies Tested */
            strategies_tested: number;
            /** Symbol */
            symbol: string;
            /** Top Results */
            top_results?: {
                [key: string]: unknown;
            }[] | null;
            /** Top Results Count */
            top_results_count: number;
        };
        /** AnalysisListResponse */
        AnalysisListResponse: {
            /** Items */
            items: components["schemas"]["AnalysisSummaryResponse"][];
        };
        /** AnalysisSummaryResponse */
        AnalysisSummaryResponse: {
            /** Close Price */
            close_price?: number | null;
            /** Completed At */
            completed_at?: string | null;
            /** Configs Tested */
            configs_tested: number;
            /** Created At */
            created_at?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Error Message */
            error_message?: string | null;
            /** Id */
            id: string;
            /** Stage */
            stage: string;
            /** Status */
            status: string;
            /** Strategies Tested */
            strategies_tested: number;
            /** Symbol */
            symbol: string;
            /** Top Results Count */
            top_results_count: number;
        };
        /** AvoidEarningsRule */
        AvoidEarningsRule: {
            /**
             * Days After
             * @default 0
             */
            days_after: number;
            /**
             * Days Before
             * @default 0
             */
            days_before: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "avoid_earnings";
        };
        /** BacktestRunDetailResponse */
        BacktestRunDetailResponse: {
            /** Account Size */
            account_size: string;
            /** Commission Per Contract */
            commission_per_contract: string;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Data Source */
            data_source: string;
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Dte Tolerance Days */
            dte_tolerance_days: number;
            /** Engine Version */
            engine_version: string;
            /** Equity Curve */
            equity_curve: components["schemas"]["EquityCurvePointResponse"][];
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Max Holding Days */
            max_holding_days: number;
            /** Risk Per Trade Pct */
            risk_per_trade_pct: string;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["RunStatus"];
            /** Strategy Type */
            strategy_type: string;
            summary: components["schemas"]["BacktestSummaryResponse"];
            /** Symbol */
            symbol: string;
            /** Target Dte */
            target_dte: number;
            /** Trades */
            trades: components["schemas"]["BacktestTradeResponse"][];
            /** Warnings */
            warnings: {
                [key: string]: unknown;
            }[];
        };
        /** BacktestRunHistoryItemResponse */
        BacktestRunHistoryItemResponse: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Max Holding Days */
            max_holding_days: number;
            status: components["schemas"]["RunStatus"];
            /** Strategy Type */
            strategy_type: string;
            summary: components["schemas"]["BacktestSummaryResponse"];
            /** Symbol */
            symbol: string;
            /** Target Dte */
            target_dte: number;
        };
        /** BacktestRunListResponse */
        BacktestRunListResponse: {
            /** Items */
            items: components["schemas"]["BacktestRunHistoryItemResponse"][];
        };
        /** BacktestRunStatusResponse */
        BacktestRunStatusResponse: {
            /** Completed At */
            completed_at?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["RunStatus"];
        };
        /** BacktestSummaryResponse */
        BacktestSummaryResponse: {
            /** Average Dte At Open */
            average_dte_at_open: string;
            /** Average Holding Period Days */
            average_holding_period_days: string;
            /** Average Loss Amount */
            average_loss_amount: string;
            /** Average Win Amount */
            average_win_amount: string;
            /** Cagr Pct */
            cagr_pct?: string | null;
            /** Calmar Ratio */
            calmar_ratio?: string | null;
            /** Ending Equity */
            ending_equity: string;
            /**
             * Expectancy
             * @default 0
             */
            expectancy: string;
            /**
             * Max Consecutive Losses
             * @default 0
             */
            max_consecutive_losses: number;
            /**
             * Max Consecutive Wins
             * @default 0
             */
            max_consecutive_wins: number;
            /** Max Drawdown Pct */
            max_drawdown_pct: string;
            /** Payoff Ratio */
            payoff_ratio?: string | null;
            /** Profit Factor */
            profit_factor?: string | null;
            /** Recovery Factor */
            recovery_factor?: string | null;
            /** Sharpe Ratio */
            sharpe_ratio?: string | null;
            /** Sortino Ratio */
            sortino_ratio?: string | null;
            /** Starting Equity */
            starting_equity: string;
            /** Total Commissions */
            total_commissions: string;
            /** Total Net Pnl */
            total_net_pnl: string;
            /** Total Roi Pct */
            total_roi_pct: string;
            /** Trade Count */
            trade_count: number;
            /** Win Rate */
            win_rate: string;
        };
        /** BacktestTradeResponse */
        BacktestTradeResponse: {
            /** Detail Json */
            detail_json?: {
                [key: string]: unknown;
            };
            /** Dte At Open */
            dte_at_open: number;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Entry Mid */
            entry_mid: string;
            /** Entry Reason */
            entry_reason: string;
            /** Entry Underlying Close */
            entry_underlying_close: string;
            /**
             * Exit Date
             * Format: date
             */
            exit_date: string;
            /** Exit Mid */
            exit_mid: string;
            /** Exit Reason */
            exit_reason: string;
            /** Exit Underlying Close */
            exit_underlying_close: string;
            /**
             * Expiration Date
             * Format: date
             */
            expiration_date: string;
            /** Gross Pnl */
            gross_pnl: string;
            /** Holding Period Days */
            holding_period_days: number;
            /** Id */
            id?: string | null;
            /** Net Pnl */
            net_pnl: string;
            /** Option Ticker */
            option_ticker: string;
            /** Quantity */
            quantity: number;
            /** Strategy Type */
            strategy_type: string;
            /** Total Commissions */
            total_commissions: string;
            /** Underlying Symbol */
            underlying_symbol: string;
        };
        /**
         * BillingInterval
         * @enum {string}
         */
        BillingInterval: "monthly" | "yearly";
        /**
         * BollingerBand
         * @enum {string}
         */
        BollingerBand: "lower" | "middle" | "upper";
        /** BollingerBandsRule */
        BollingerBandsRule: {
            band: components["schemas"]["BollingerBand"];
            operator: components["schemas"]["ComparisonOperator"];
            /**
             * Period
             * @default 20
             */
            period: number;
            /**
             * Standard Deviations
             * @default 2
             */
            standard_deviations: number | string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bollinger_bands";
        };
        /** CheckoutSessionResponse */
        CheckoutSessionResponse: {
            /** Billing Interval */
            billing_interval: string;
            /** Checkout Url */
            checkout_url: string;
            /** Expires At */
            expires_at?: string | null;
            /** Session Id */
            session_id: string;
            /** Tier */
            tier: string;
        };
        /** CompareBacktestsRequest */
        CompareBacktestsRequest: {
            /** Run Ids */
            run_ids: string[];
        };
        /** CompareBacktestsResponse */
        CompareBacktestsResponse: {
            /** Comparison Limit */
            comparison_limit: number;
            /** Items */
            items: components["schemas"]["BacktestRunDetailResponse"][];
        };
        /**
         * ComparisonOperator
         * @enum {string}
         */
        ComparisonOperator: "lt" | "lte" | "gt" | "gte";
        /** CreateAnalysisRequest */
        CreateAnalysisRequest: {
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Symbol */
            symbol: string;
        };
        /** CreateBacktestRunRequest */
        CreateBacktestRunRequest: {
            /** Account Size */
            account_size: number | string;
            /** Commission Per Contract */
            commission_per_contract: number | string;
            /** Custom Legs */
            custom_legs?: components["schemas"]["CustomLegDefinition"][] | null;
            /**
             * Dte Tolerance Days
             * @default 5
             */
            dte_tolerance_days: number;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Entry Rules */
            entry_rules?: (components["schemas"]["RsiRule"] | components["schemas"]["MovingAverageCrossoverRule"] | components["schemas"]["MacdRule"] | components["schemas"]["BollingerBandsRule"] | components["schemas"]["IvRankRule"] | components["schemas"]["IvPercentileRule"] | components["schemas"]["VolumeSpikeRule"] | components["schemas"]["SupportResistanceRule"] | components["schemas"]["AvoidEarningsRule"])[];
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Max Holding Days */
            max_holding_days: number;
            /** Risk Per Trade Pct */
            risk_per_trade_pct: number | string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** @description Optional overrides for strike placement and spread width */
            strategy_overrides?: components["schemas"]["StrategyOverrides"] | null;
            strategy_type: components["schemas"]["StrategyType"];
            /** Symbol */
            symbol: string;
            /** Target Dte */
            target_dte: number;
        };
        /** CreateCheckoutSessionRequest */
        CreateCheckoutSessionRequest: {
            /** @default monthly */
            billing_interval: components["schemas"]["BillingInterval"];
            /**
             * Tier
             * @enum {string}
             */
            tier: "pro" | "premium";
        };
        /** CreateExportRequest */
        CreateExportRequest: {
            format: components["schemas"]["ExportFormat"];
            /** Idempotency Key */
            idempotency_key?: string | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** CreatePortalSessionRequest */
        CreatePortalSessionRequest: {
            /**
             * Return Path
             * @default /app/settings/billing
             */
            return_path: string | null;
        };
        /** CreateScannerJobRequest */
        CreateScannerJobRequest: {
            /** Account Size */
            account_size: number | string;
            /** Commission Per Contract */
            commission_per_contract: number | string;
            /**
             * Dte Tolerance Days
             * @default 5
             */
            dte_tolerance_days: number;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Max Holding Days */
            max_holding_days: number;
            /**
             * Max Recommendations
             * @default 10
             */
            max_recommendations: number;
            /** @default basic */
            mode: components["schemas"]["ScannerMode"];
            /** Name */
            name?: string | null;
            /**
             * Refresh Daily
             * @default false
             */
            refresh_daily: boolean;
            /**
             * Refresh Priority
             * @default 50
             */
            refresh_priority: number;
            /** Risk Per Trade Pct */
            risk_per_trade_pct: number | string;
            /** Rule Sets */
            rule_sets: components["schemas"]["RuleSetDefinition"][];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Strategy Types */
            strategy_types: components["schemas"]["StrategyType"][];
            /** Symbols */
            symbols: string[];
            /** Target Dte */
            target_dte: number;
        };
        /** CreateTemplateRequest */
        CreateTemplateRequest: {
            config: components["schemas"]["TemplateConfig"];
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
        };
        /**
         * CrossoverDirection
         * @enum {string}
         */
        CrossoverDirection: "bullish" | "bearish";
        /** CurrentUserResponse */
        CurrentUserResponse: {
            /**
             * Cancel At Period End
             * @default false
             */
            cancel_at_period_end: boolean;
            /** Clerk User Id */
            clerk_user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string | null;
            features: components["schemas"]["FeatureAccessResponse"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Plan Tier */
            plan_tier: string;
            /** Subscription Billing Interval */
            subscription_billing_interval?: string | null;
            /** Subscription Current Period End */
            subscription_current_period_end?: string | null;
            /** Subscription Status */
            subscription_status?: string | null;
            usage: components["schemas"]["UsageSummaryResponse"];
        };
        /**
         * CustomLegDefinition
         * @description User-defined leg for custom N-leg strategies.
         */
        CustomLegDefinition: {
            /**
             * Asset Type
             * @default option
             * @enum {string}
             */
            asset_type: "option" | "stock";
            /** Contract Type */
            contract_type?: ("call" | "put") | null;
            /**
             * Expiration Offset
             * @description 0=primary expiration, 1=next available, 2=second-next.
             * @default 0
             */
            expiration_offset: number;
            /**
             * Quantity Ratio
             * @default 1
             */
            quantity_ratio: number;
            /**
             * Side
             * @enum {string}
             */
            side: "long" | "short";
            /**
             * Strike Offset
             * @description Strike offset from ATM in listed-strike steps. 0=ATM, +1=one OTM call step, -1=one OTM put step.
             * @default 0
             */
            strike_offset: number;
        };
        /** DailyPickItemResponse */
        DailyPickItemResponse: {
            /** Close Price */
            close_price: number;
            /** Config Snapshot */
            config_snapshot?: {
                [key: string]: unknown;
            };
            /** Forecast */
            forecast?: {
                [key: string]: unknown;
            };
            /** Rank */
            rank: number;
            /** Regime Labels */
            regime_labels?: string[];
            /** Score */
            score: number;
            /** Strategy Type */
            strategy_type: string;
            /** Summary */
            summary?: {
                [key: string]: unknown;
            };
            /** Symbol */
            symbol: string;
            /** Target Dte */
            target_dte: number;
        };
        /** DailyPicksResponse */
        DailyPicksResponse: {
            /** Items */
            items?: components["schemas"]["DailyPickItemResponse"][];
            /** Pipeline Run Id */
            pipeline_run_id?: string | null;
            pipeline_stats?: components["schemas"]["PipelineStatsResponse"] | null;
            /** Status */
            status: string;
            /** Trade Date */
            trade_date?: string | null;
        };
        /** EquityCurvePointResponse */
        EquityCurvePointResponse: {
            /** Cash */
            cash: string;
            /** Drawdown Pct */
            drawdown_pct: string;
            /** Equity */
            equity: string;
            /** Position Value */
            position_value: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /**
         * ExportFormat
         * @enum {string}
         */
        ExportFormat: "csv" | "pdf";
        /** ExportJobResponse */
        ExportJobResponse: {
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Export Format */
            export_format: string;
            /** File Name */
            file_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mime Type */
            mime_type: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Size Bytes
             * @default 0
             */
            size_bytes: number;
            /** Status */
            status: string;
        };
        /** FeatureAccessResponse */
        FeatureAccessResponse: {
            /** Export Formats */
            export_formats?: string[];
            /** Forecasting Access */
            forecasting_access: boolean;
            /** History Days */
            history_days?: number | null;
            /** History Item Limit */
            history_item_limit: number;
            /** Monthly Backtest Quota */
            monthly_backtest_quota?: number | null;
            /** Plan Tier */
            plan_tier: string;
            /** Scanner Modes */
            scanner_modes?: string[];
            /** Side By Side Comparison Limit */
            side_by_side_comparison_limit: number;
        };
        /** ForecastEnvelopeResponse */
        ForecastEnvelopeResponse: {
            /** Expected Move Abs Pct */
            expected_move_abs_pct: string;
            forecast: components["schemas"]["HistoricalAnalogForecastResponse"];
            /**
             * Probabilistic Note
             * @default This range is probabilistic, derived from historical analog setups, and is not financial advice or a certainty of future results.
             */
            probabilistic_note: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoricalAnalogForecastResponse */
        HistoricalAnalogForecastResponse: {
            /** Analog Count */
            analog_count: number;
            /** Analog Dates */
            analog_dates?: string[];
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Disclaimer */
            disclaimer: string;
            /** Expected Return High Pct */
            expected_return_high_pct: string;
            /** Expected Return Low Pct */
            expected_return_low_pct: string;
            /** Expected Return Median Pct */
            expected_return_median_pct: string;
            /** Horizon Days */
            horizon_days: number;
            /** Positive Outcome Rate Pct */
            positive_outcome_rate_pct: string;
            /** Strategy Type */
            strategy_type?: string | null;
            /** Summary */
            summary: string;
            /** Symbol */
            symbol: string;
        };
        /** HistoricalPerformanceResponse */
        HistoricalPerformanceResponse: {
            /** Last Observed At */
            last_observed_at?: string | null;
            /**
             * Recency Half Life Days
             * @default 180
             */
            recency_half_life_days: number;
            /**
             * Sample Count
             * @default 0
             */
            sample_count: number;
            /**
             * Weighted Max Drawdown Pct
             * @default 0
             */
            weighted_max_drawdown_pct: string;
            /**
             * Weighted Total Net Pnl
             * @default 0
             */
            weighted_total_net_pnl: string;
            /**
             * Weighted Total Roi Pct
             * @default 0
             */
            weighted_total_roi_pct: string;
            /**
             * Weighted Win Rate
             * @default 0
             */
            weighted_win_rate: string;
        };
        /** IvPercentileRule */
        IvPercentileRule: {
            /**
             * Lookback Days
             * @default 252
             */
            lookback_days: number;
            operator: components["schemas"]["ComparisonOperator"];
            /** Threshold */
            threshold: number | string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "iv_percentile";
        };
        /** IvRankRule */
        IvRankRule: {
            /**
             * Lookback Days
             * @default 252
             */
            lookback_days: number;
            operator: components["schemas"]["ComparisonOperator"];
            /** Threshold */
            threshold: number | string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "iv_rank";
        };
        /** MacdRule */
        MacdRule: {
            direction: components["schemas"]["CrossoverDirection"];
            /**
             * Fast Period
             * @default 12
             */
            fast_period: number;
            /**
             * Signal Period
             * @default 9
             */
            signal_period: number;
            /**
             * Slow Period
             * @default 26
             */
            slow_period: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "macd";
        };
        /** MovingAverageCrossoverRule */
        MovingAverageCrossoverRule: {
            direction: components["schemas"]["CrossoverDirection"];
            /** Fast Period */
            fast_period: number;
            /** Slow Period */
            slow_period: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ema_crossover" | "sma_crossover";
        };
        /** PipelineHistoryItemResponse */
        PipelineHistoryItemResponse: {
            /** Completed At */
            completed_at?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Error Message */
            error_message?: string | null;
            /** Id */
            id: string;
            /** Recommendations Produced */
            recommendations_produced: number;
            /** Status */
            status: string;
            /** Symbols Screened */
            symbols_screened: number;
            /** Trade Date */
            trade_date: string;
        };
        /** PipelineHistoryResponse */
        PipelineHistoryResponse: {
            /** Items */
            items: components["schemas"]["PipelineHistoryItemResponse"][];
        };
        /** PipelineStatsResponse */
        PipelineStatsResponse: {
            /** Completed At */
            completed_at?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Full Backtests Run */
            full_backtests_run: number;
            /** Pairs Generated */
            pairs_generated: number;
            /** Quick Backtests Run */
            quick_backtests_run: number;
            /** Recommendations Produced */
            recommendations_produced: number;
            /** Symbols After Screen */
            symbols_after_screen: number;
            /** Symbols Screened */
            symbols_screened: number;
        };
        /** PortalSessionResponse */
        PortalSessionResponse: {
            /** Portal Url */
            portal_url: string;
        };
        /** RankingBreakdownResponse */
        RankingBreakdownResponse: {
            /** Current Performance Score */
            current_performance_score: string;
            /** Final Score */
            final_score: string;
            /** Forecast Alignment Score */
            forecast_alignment_score: string;
            /** Historical Performance Score */
            historical_performance_score: string;
            /** Reasoning */
            reasoning?: string[];
        };
        /** RsiRule */
        RsiRule: {
            operator: components["schemas"]["ComparisonOperator"];
            /**
             * Period
             * @default 14
             */
            period: number;
            /** Threshold */
            threshold: number | string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "rsi";
        };
        /** RuleSetDefinition */
        RuleSetDefinition: {
            /** Entry Rules */
            entry_rules?: (components["schemas"]["RsiRule"] | components["schemas"]["MovingAverageCrossoverRule"] | components["schemas"]["MacdRule"] | components["schemas"]["BollingerBandsRule"] | components["schemas"]["IvRankRule"] | components["schemas"]["IvPercentileRule"] | components["schemas"]["VolumeSpikeRule"] | components["schemas"]["SupportResistanceRule"] | components["schemas"]["AvoidEarningsRule"])[];
            /** Name */
            name: string;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** ScannerJobListResponse */
        ScannerJobListResponse: {
            /** Items */
            items: components["schemas"]["ScannerJobResponse"][];
        };
        /** ScannerJobResponse */
        ScannerJobResponse: {
            /** Candidate Count */
            candidate_count: number;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Evaluated Candidate Count */
            evaluated_candidate_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Job Kind */
            job_kind: string;
            mode: components["schemas"]["ScannerMode"];
            /** Name */
            name: string | null;
            /** Plan Tier Snapshot */
            plan_tier_snapshot: string;
            /** Recommendation Count */
            recommendation_count: number;
            /** Refresh Daily */
            refresh_daily: boolean;
            /** Refresh Priority */
            refresh_priority: number;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["ScannerJobStatus"];
            /** Warnings */
            warnings?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * ScannerJobStatus
         * @enum {string}
         */
        ScannerJobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * ScannerMode
         * @enum {string}
         */
        ScannerMode: "basic" | "advanced";
        /** ScannerRecommendationListResponse */
        ScannerRecommendationListResponse: {
            /** Items */
            items: components["schemas"]["ScannerRecommendationResponse"][];
        };
        /** ScannerRecommendationResponse */
        ScannerRecommendationResponse: {
            /** Equity Curve */
            equity_curve?: components["schemas"]["EquityCurvePointResponse"][];
            forecast: components["schemas"]["HistoricalAnalogForecastResponse"];
            historical_performance: components["schemas"]["HistoricalPerformanceResponse"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rank */
            rank: number;
            ranking_breakdown: components["schemas"]["RankingBreakdownResponse"];
            /** Request Snapshot */
            request_snapshot: {
                [key: string]: unknown;
            };
            /** Rule Set Name */
            rule_set_name: string;
            /** Score */
            score: string;
            /** Strategy Type */
            strategy_type: string;
            summary: components["schemas"]["BacktestSummaryResponse"];
            /** Symbol */
            symbol: string;
            /** Trades */
            trades?: components["schemas"]["BacktestTradeResponse"][];
            /** Warnings */
            warnings?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * SpreadWidthConfig
         * @description Configuration for how wide a spread's wings are.
         */
        SpreadWidthConfig: {
            /** @default strike_steps */
            mode: components["schemas"]["SpreadWidthMode"];
            /**
             * Value
             * @default 1
             */
            value: number | string;
        };
        /**
         * SpreadWidthMode
         * @description How to determine the width of a spread (distance between short and long strikes).
         * @enum {string}
         */
        SpreadWidthMode: "strike_steps" | "dollar_width" | "pct_width";
        /** StrategyCatalogGroupResponse */
        StrategyCatalogGroupResponse: {
            /** Category */
            category: string;
            /** Category Label */
            category_label: string;
            /** Strategies */
            strategies: components["schemas"]["StrategyCatalogItemResponse"][];
        };
        /** StrategyCatalogItemResponse */
        StrategyCatalogItemResponse: {
            /** Bias */
            bias: string;
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Leg Count */
            leg_count: number;
            /** Max Loss Description */
            max_loss_description: string;
            /** Min Tier */
            min_tier: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Short Description */
            short_description: string;
            /** Strategy Type */
            strategy_type: string;
            /** Tags */
            tags?: string[];
        };
        /** StrategyCatalogResponse */
        StrategyCatalogResponse: {
            /** Groups */
            groups: components["schemas"]["StrategyCatalogGroupResponse"][];
            /** Total Strategies */
            total_strategies: number;
        };
        /**
         * StrategyOverrides
         * @description Optional overrides for how a strategy selects strikes and widths.
         *
         *     Named fields correspond to standard leg roles. Strategies ignore fields
         *     that don't apply to them (e.g., a long call ignores ``short_call_strike``).
         */
        StrategyOverrides: {
            /** @description Override long call placement (for diagonals, PMCC) */
            long_call_strike?: components["schemas"]["StrikeSelection"] | null;
            /** @description Override long put placement */
            long_put_strike?: components["schemas"]["StrikeSelection"] | null;
            /** @description Override short call placement */
            short_call_strike?: components["schemas"]["StrikeSelection"] | null;
            /** @description Override short put placement */
            short_put_strike?: components["schemas"]["StrikeSelection"] | null;
            /** @description Override wing/spread width for strategies with protection legs */
            spread_width?: components["schemas"]["SpreadWidthConfig"] | null;
        };
        /**
         * StrategyType
         * @enum {string}
         */
        StrategyType: "long_call" | "long_put" | "covered_call" | "cash_secured_put" | "bull_call_debit_spread" | "bear_put_debit_spread" | "bull_put_credit_spread" | "bear_call_credit_spread" | "iron_condor" | "long_straddle" | "long_strangle" | "calendar_spread" | "butterfly" | "wheel_strategy" | "poor_mans_covered_call" | "ratio_call_backspread" | "ratio_put_backspread" | "collar" | "diagonal_spread" | "double_diagonal" | "short_straddle" | "short_strangle" | "covered_strangle" | "synthetic_put" | "reverse_conversion" | "jade_lizard" | "iron_butterfly" | "custom_2_leg" | "custom_3_leg" | "custom_4_leg" | "custom_5_leg" | "custom_6_leg" | "custom_8_leg" | "naked_call" | "naked_put";
        /**
         * StrikeSelection
         * @description Configuration for where a strategy leg's strike is placed relative to the underlying.
         */
        StrikeSelection: {
            /** @default nearest_otm */
            mode: components["schemas"]["StrikeSelectionMode"];
            /**
             * Value
             * @description Interpretation depends on mode: pct_from_spot → percentage, atm_offset_steps → integer steps, delta_target → absolute delta (0-100).
             */
            value?: number | string | null;
        };
        /**
         * StrikeSelectionMode
         * @description How to choose a strike for a strategy leg.
         * @enum {string}
         */
        StrikeSelectionMode: "nearest_otm" | "pct_from_spot" | "atm_offset_steps" | "delta_target";
        /**
         * SupportResistanceMode
         * @enum {string}
         */
        SupportResistanceMode: "near_support" | "near_resistance" | "breakout_above_resistance" | "breakdown_below_support";
        /** SupportResistanceRule */
        SupportResistanceRule: {
            /**
             * Lookback Period
             * @default 20
             */
            lookback_period: number;
            mode: components["schemas"]["SupportResistanceMode"];
            /**
             * Tolerance Pct
             * @default 1.0
             */
            tolerance_pct: number | string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "support_resistance";
        };
        /**
         * TemplateConfig
         * @description The reusable portion of a backtest configuration — everything except symbol and dates.
         */
        TemplateConfig: {
            /** Account Size */
            account_size: number | string;
            /** Commission Per Contract */
            commission_per_contract: number | string;
            /** Default Symbol */
            default_symbol?: string | null;
            /**
             * Dte Tolerance Days
             * @default 5
             */
            dte_tolerance_days: number;
            /** Entry Rules */
            entry_rules?: (components["schemas"]["RsiRule"] | components["schemas"]["MovingAverageCrossoverRule"] | components["schemas"]["MacdRule"] | components["schemas"]["BollingerBandsRule"] | components["schemas"]["IvRankRule"] | components["schemas"]["IvPercentileRule"] | components["schemas"]["VolumeSpikeRule"] | components["schemas"]["SupportResistanceRule"] | components["schemas"]["AvoidEarningsRule"])[];
            /** Max Holding Days */
            max_holding_days: number;
            /** Risk Per Trade Pct */
            risk_per_trade_pct: number | string;
            strategy_type: components["schemas"]["StrategyType"];
            /** Target Dte */
            target_dte: number;
        };
        /** TemplateListResponse */
        TemplateListResponse: {
            /** Items */
            items: components["schemas"]["TemplateResponse"][];
            /** Template Limit */
            template_limit?: number | null;
            /** Total */
            total: number;
        };
        /** TemplateResponse */
        TemplateResponse: {
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Strategy Type */
            strategy_type: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UpdateTemplateRequest */
        UpdateTemplateRequest: {
            config?: components["schemas"]["TemplateConfig"] | null;
            /**
             * Description
             * @default UNSET
             */
            description: (string | components["schemas"]["_Unset"]) | null;
            /** Name */
            name?: string | null;
        };
        /** UsageSummaryResponse */
        UsageSummaryResponse: {
            /** Backtests Remaining This Month */
            backtests_remaining_this_month?: number | null;
            /**
             * Backtests Used This Month
             * @default 0
             */
            backtests_used_this_month: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VolumeSpikeRule */
        VolumeSpikeRule: {
            /**
             * Lookback Period
             * @default 20
             */
            lookback_period: number;
            /**
             * Multiplier
             * @default 1.5
             */
            multiplier: number | string;
            /** @default gte */
            operator: components["schemas"]["ComparisonOperator"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "volume_spike";
        };
        /**
         * _Unset
         * @enum {string}
         */
        _Unset: "UNSET";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_analyses_v1_analysis_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_v1_analysis_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_v1_analysis__analysis_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_status_v1_analysis__analysis_id__status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backtests_v1_backtests_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_backtest_v1_backtests_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBacktestRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_backtests_v1_backtests_compare_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareBacktestsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareBacktestsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_v1_backtests__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_status_v1_backtests__run_id__status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_checkout_session_v1_billing_checkout_session_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckoutSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_portal_session_v1_billing_portal_session_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePortalSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stripe_webhook_v1_billing_webhook_post: {
        parameters: {
            query?: never;
            header: {
                "Stripe-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_daily_picks_v1_daily_picks_get: {
        parameters: {
            query?: {
                trade_date?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyPicksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pipeline_history_v1_daily_picks_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analysis_events_v1_events_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_events_v1_events_backtests__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_events_v1_events_exports__export_job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                export_job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_events_v1_events_scans__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_export_v1_exports_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_v1_exports__export_job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                export_job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_export_status_v1_exports__export_job_id__status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                export_job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forecast_v1_forecasts__ticker__get: {
        parameters: {
            query?: {
                strategy_type?: components["schemas"]["StrategyType"] | null;
                horizon_days?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastEnvelopeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meta_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_scans_v1_scans_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannerJobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_scan_v1_scans_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScannerJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannerJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_v1_scans__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannerJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_recommendations_v1_scans__job_id__recommendations_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannerRecommendationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_strategy_catalog_v1_strategy_catalog_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyCatalogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_v1_templates_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_v1_templates_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_v1_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_v1_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_template_v1_templates__template_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTemplateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
