port 0
bind 0.0.0.0
protected-mode yes
appendonly yes
save 60 1000

tls-port 6380
tls-cert-file /run/secrets/redis.crt
tls-key-file /run/secrets/redis.key
tls-ca-cert-file /run/secrets/redis-ca.crt
tls-auth-clients yes
